---
- name: Install GnuCash and configure it with customizations
  become: yes
  hosts: all
  gather_facts: no
  pre_tasks:
  - name: Install GnuCash and other needed packages
    dnf: name={{ item }} state=present
    with_items:
    - gnucash
    - perl-Finance-Quote
    - libdbi-dbd-sqlite

  - name: Get Finance::Quote path
    command: perldoc -ml Finance::Quote
    changed_when: no
    register: quote_path_output

  - name: Set finance_quote_path variable
    set_fact: finance_quote_path={{ quote_path_output.stdout | regex_replace('\.pm','') }}
    changed_when: no

  tasks:
  - name: Add Bloomberg quote source
    get_url:
      # TODO get bloomberg from my fork until PR#1 is accepted upstream
      #url: 'https://raw.githubusercontent.com/alex314159/PerlFinanceQuoteBloomberg/master/Bloomberg.pm'
      url: 'https://raw.githubusercontent.com/tomason/PerlFinanceQuoteBloomberg/patch-1/Bloomberg.pm'
      dest: '{{ finance_quote_path }}/Bloomberg.pm'
      force: yes

  - name: Add Pioneer Investments quote source
    copy: src=PioneerInvestments.pm dest='{{ finance_quote_path }}/PioneerInvestments.pm'

  # TODO add any other custom sources

  - name: Configure Finance::Quote to include custom modules by default
    lineinfile:
      dest: '{{ finance_quote_path }}.pm'
      line: "  push(@modules, qw/Bloomberg PioneerInvestments/ );"
      insertbefore: '$this->_load_modules(@modules,@reqmodules);'
      regexp: '^  push(@modules, .* );$'
      state: present
